In [1]:
import numpy as np

In [5]:
arr = np.random.rand(3,6)
arr

array([[0.09603829, 0.71188649, 0.04863446, 0.83821355, 0.11400251,
        0.76219349],
       [0.53962383, 0.01440337, 0.04989907, 0.75892077, 0.39560077,
        0.49061259],
       [0.30995681, 0.92087709, 0.37542456, 0.26728486, 0.21180386,
        0.38467724]])

In [12]:
np.sum(arr)

np.float64(7.290053608249599)

In [18]:
np.sum(arr,axis=0)

array([0.94561893, 1.64716694, 0.4739581 , 1.86441919, 0.72140714,
       1.63748331])

In [7]:
np.mean(arr)

np.float64(0.40500297823608883)

In [19]:
np.mean(arr,axis=1)

array([0.4284948 , 0.3748434 , 0.41167074])

In [20]:
np.cumsum(arr)

array([0.09603829, 0.80792478, 0.85655924, 1.69477279, 1.8087753 ,
       2.57096878, 3.11059261, 3.12499598, 3.17489505, 3.93381583,
       4.3294166 , 4.82002919, 5.129986  , 6.05086309, 6.42628765,
       6.69357251, 6.90537637, 7.29005361])

In [8]:
np.min(arr)

np.float64(0.014403368592840748)

In [9]:
np.max(arr)

np.float64(0.9208770901297951)