In [2]:
import numpy as np

In [19]:
data = np.random.rand(4)
data

array([0.18434632, 0.39308466, 0.2013978 , 0.42265527])

In [20]:
np.sort(data)

array([0.18434632, 0.2013978 , 0.39308466, 0.42265527])

In [21]:
-np.sort(-data)

array([0.42265527, 0.39308466, 0.2013978 , 0.18434632])

In [22]:
arr2d = np.random.rand(8).reshape(2,4)
arr2d

array([[0.61700859, 0.50610895, 0.20964987, 0.6822378 ],
       [0.47503019, 0.20935499, 0.82287291, 0.59365496]])

In [23]:
np.sort(arr2d, axis=0)

array([[0.47503019, 0.20935499, 0.20964987, 0.59365496],
       [0.61700859, 0.50610895, 0.82287291, 0.6822378 ]])

In [24]:
np.sort(arr2d, axis=1)

array([[0.20964987, 0.50610895, 0.61700859, 0.6822378 ],
       [0.20935499, 0.47503019, 0.59365496, 0.82287291]])

In [26]:
np.sort(arr2d)

array([[0.20964987, 0.50610895, 0.61700859, 0.6822378 ],
       [0.20935499, 0.47503019, 0.59365496, 0.82287291]])