In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,10)

In [ ]:
np.save("data.npy", arr)

In [ ]:
np.load('data.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1 = np.random.rand(2,6)

In [ ]:
np.savez("data1", a=arr, b=arr1)

In [17]:
data1 = np.load("data1.npz")
data1

NpzFile 'data1.npz' with keys: a, b

In [18]:
data1['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
data1['b']

array([[0.45316448, 0.25468583, 0.51309507, 0.28508966, 0.30340579,
        0.24746751],
       [0.80991204, 0.23458244, 0.2694659 , 0.38102948, 0.48333637,
        0.6787557 ]])

In [21]:
np.savez_compressed("data2", a=arr, b=arr1)
data2 = np.load("data2.npz")
data2['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])