In [2]:
import numpy as np

In [13]:
x = np.random.rand(2,3)
y = np.random.rand(2,3)

In [14]:
x+y

array([[0.63417071, 1.32805108, 0.97974042],
       [1.12386492, 0.74317898, 0.71815277]])

In [15]:
y-x

array([[-0.5775153 , -0.33409058, -0.96661219],
       [-0.84025297, -0.68411815,  0.22094038]])

In [7]:
x*y

array([[0.16454658, 0.26810316, 0.01494966],
       [0.29163487, 0.02185571, 0.04067659]])

In [8]:
x*5

array([[4.83144485, 3.1145301 , 0.9796749 ],
       [3.30809718, 1.30362496, 4.44767535]])

In [16]:
y=np.random.rand(3,2)

In [17]:
np.dot(x,y)

array([[1.1184459 , 0.97095232],
       [0.9471102 , 0.91250049]])

In [18]:
from numpy.linalg import inv