In [4]:
import numpy as np

In [6]:
data1 = [3.5, 5, -3, 2]
arr1 = np.array(data1)
arr1

array([ 3.5,  5. , -3. ,  2. ])

In [5]:
data2 = (4,6,8,-8)
arr2 = np.array(data2)
arr2

array([ 4,  6,  8, -8])

In [7]:
data3 = [[1,2,3],[4,5,6]]
arr3 = np.array(data3)
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr3.ndim

2


arr_name.shape - arr_name - arr_name arrayining qator va ustunlar sonini beradi

arr_name.size - arr_name arrayi ichidagi ma'lumotlar soni

In [10]:
arr3.shape

(2, 3)

In [9]:
arr3.size

6


arr = np.zeros(shape = (2, 4)) - faqat 0 dan iborat massiv yaratadi, shape yozish majburiy

arr = np.ones(shape = (2, 4)) - faqat 1 dan iborat massiv yaratadi, shape yozish majburiy

In [11]:
zero_arr = np.zeros(shape=(2,4))
zero_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
one_arr = np.ones(shape = (2,4))
one_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

arr = np.arange(1,10,2) - pythondagi range funksiyasi bilan bir hil

In [15]:
r_arr = np.arange(1,100,4)
r_arr

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])