In [ ]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [4]:
arr2 = np.array([1,2,3], dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [5]:
arr2.dtype

dtype('int32')

In [6]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [7]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [8]:
data = np.array([1,2.5,4.3,5])
new_data = data.astype(np.int32)
new_data

array([1, 2, 4, 5], dtype=int32)

In [ ]:
import numpy as np