In [2]:
import numpy as np

In [3]:
arr = np.arange(10,100,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [4]:
arr[4]

np.int64(30)

In [5]:
arr[-14]

np.int64(30)

In [6]:
arr[3:10]

array([25, 30, 35, 40, 45, 50, 55])


array = arr[3:5].copy() - arrayga arrdan nusxalaydi va asl massivga ta'sir ko'rsatmayd

In [7]:
copied_array = arr[3:5].copy()
copied_array

array([25, 30])

In [9]:
copied_array[:] = 0
copied_array

array([0, 0])

In [11]:
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [12]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr2d_slice = arr2d[2,1]
arr2d_slice

np.int64(8)

In [15]:
arr3d = np.array([
    [[1,2,3],
     [4,5,6],
     [7,8,9]],

    [[10,11,12],
     [13,14,15],
     [16,17,18]],

    [[19,20,21],
     [22,23,24],
     [25,26,27]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [18]:
arr3d[1][2,0]

np.int64(16)

In [19]:
arr3d[0][0]

array([1, 2, 3])