In [ ]:
import numpy as np

In [ ]:
names = np.array(['Hasan', 'Husan', 'Alisher', 'Yusuf'])
names

array(['Hasan', 'Husan', 'Alisher', 'Yusuf'], dtype='<U7')

In [ ]:
data = np.random.randn(4,4)
data

array([[-0.33328438, -1.09507388, -0.90694232,  0.08894029],
       [ 0.8164599 ,  0.35150166,  0.30435051,  0.26515727],
       [-0.62489988,  0.99212868, -0.31383932, -0.42613302],
       [ 0.35915322, -1.16013211, -1.47755858,  0.24038601]])

In [ ]:
names == 'Hasan'

array([ True, False, False, False])

In [ ]:
data[names == 'Hasan']

array([[-0.33328438, -1.09507388, -0.90694232,  0.08894029]])

In [ ]:
data[names == 'Hasan', 1:]

array([[-1.09507388, -0.90694232,  0.08894029]])

In [ ]:
data[names != 'Hasan']

array([[ 0.8164599 ,  0.35150166,  0.30435051,  0.26515727],
       [-0.62489988,  0.99212868, -0.31383932, -0.42613302],
       [ 0.35915322, -1.16013211, -1.47755858,  0.24038601]])

In [ ]:
data[names != 'Hasan',2:]

array([[ 0.30435051,  0.26515727],
       [-0.31383932, -0.42613302],
       [-1.47755858,  0.24038601]])

In [ ]:
mask = (names == 'Hasan') | (names == 'Husan')
mask

array([ True,  True, False, False])

In [ ]:
data[mask]

array([[-0.33328438, -1.09507388, -0.90694232,  0.08894029],
       [ 0.8164599 ,  0.35150166,  0.30435051,  0.26515727]])

In [ ]:
data[data<0]=0
data

array([[0.        , 0.        , 0.        , 0.08894029],
       [0.8164599 , 0.35150166, 0.30435051, 0.26515727],
       [0.        , 0.99212868, 0.        , 0.        ],
       [0.35915322, 0.        , 0.        , 0.24038601]])