In [ ]:
import numpy as np

In [ ]:
arr = np.arange(6).reshape(3,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr_t = arr.T
arr_t

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
arr_s = arr.swapaxes(1,0)
arr_s

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
np.dot(arr, arr.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])