In [1]:
import numpy as np

In [2]:
arr = np.sqrt(4)
arr

np.float64(2.0)

In [4]:
arr = np.square(2)
arr

np.int64(4)

In [25]:
arr1 = np.random.rand(5)
arr1

array([0.88441287, 0.2179406 , 0.8195227 , 0.26504877, 0.82360349])

In [6]:
np.exp(arr1)

array([1.53708663, 1.87552016, 1.46535077, 2.11703422, 1.35218299])

In [7]:
np.log(arr1)

array([-0.84422864, -0.46380521, -0.96208694, -0.28766053, -1.19825479])

In [8]:
np.sign(arr1)

array([1., 1., 1., 1., 1.])

In [26]:
arr2,arr3 = np.modf(arr1)
print(arr2)
print(arr3)

[0.88441287 0.2179406  0.8195227  0.26504877 0.82360349]
[0. 0. 0. 0. 0.]


In [27]:
np.add(arr2,arr3)

array([0.88441287, 0.2179406 , 0.8195227 , 0.26504877, 0.82360349])

In [31]:
arr1[0] = np.nan
arr1

array([       nan, 0.2179406 , 0.8195227 , 0.26504877, 0.82360349])

In [32]:
np.isnan(arr1)

array([ True, False, False, False, False])

In [33]:
np.multiply(arr2,arr3)

array([0., 0., 0., 0., 0.])

In [34]:
np.maximum(arr2,arr2)

array([0.88441287, 0.2179406 , 0.8195227 , 0.26504877, 0.82360349])