In [1]:
import numpy as np

In [5]:
xarr = np.random.rand(5)
print(xarr)
yarr = np.random.rand(5)
print(yarr)
cond = np.array([True, False, True, False, True])

[0.7305376  0.89260055 0.10755994 0.43871313 0.66419015]
[0.31234526 0.68551166 0.17005692 0.43941457 0.40386075]


In [6]:
result = np.where(cond,xarr,yarr)
result

array([0.7305376 , 0.68551166, 0.10755994, 0.43941457, 0.66419015])

In [8]:
arr1 = np.random.rand(4,4)
arr1

array([[0.97943238, 0.79334399, 0.74741171, 0.4560954 ],
       [0.55223066, 0.23169837, 0.01108174, 0.76222548],
       [0.76285087, 0.49020188, 0.46495201, 0.09339142],
       [0.75828793, 0.90280551, 0.89642957, 0.23249797]])

In [9]:
results = np.where(arr1<0.1, -2,2)
results

array([[ 2,  2,  2,  2],
       [ 2,  2, -2,  2],
       [ 2,  2,  2, -2],
       [ 2,  2,  2,  2]])