In [1]:
import numpy as np

In [10]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(6,12).reshape(2,3)
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
arr1*arr2

array([[ 0,  7, 16],
       [27, 40, 55]])

In [13]:
arr2/arr1

<ipython-input-13-e2e60495effe>:1: RuntimeWarning: divide by zero encountered in divide
  arr2/arr1


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [14]:
arr1+arr2

array([[ 6,  8, 10],
       [12, 14, 16]])

In [15]:
arr2-arr1

array([[6, 6, 6],
       [6, 6, 6]])

In [16]:
arr1**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [19]:
arr1**0.5

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])